### ISSUE TITLE
Certaines images manquantes

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#105]
Les images repères des IDs suivants n'existe pas ou plus :
- 77
- 95
- 124
- 137
- 161
- 162
- 163
- 164
- 205
- 219
- 220
- 230

**Comment by BurkhalterY** [comment]
Le problème venait des majuscules/minuscules qui ont une influence dans l'URL sur le serveur hébergé. Cependant certaines images sont toujours introuvables :
- 137
- 161
- 162
- 163
- 164

**Comment by DidierViret** [comment]
Toutes les images ont été contrôlées et ajoutées sur le serveur de prod.
