### ISSUE TITLE
Donner la possibilité de supprimer le filtre dans la liste de sujets

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/gestion_questionnaires#124]
Pour le moment, le seul moyen de le faire est en cliquant sur Sujets dans la barre de navigation.

Il faudrait ajouter l'option "Supprimer le filtre", comme dans Questions.

**Comment by BurkhalterY** [comment]
Ne sera peut-être plus nécessaires car l'interface des sujets et des modules a été refait dans la branche BuYa.
