### ISSUE TITLE
Corriger la régénération de questionnaires et de corrigés ne fonctionne pas

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#135]
La régénération ne fonctionne pas.
1. Générer un questionnaire
2. Modifier le texte d'une des questions de ce questionnaire
3. Régénérer le questionnaire
4. Vérifier que le nouveau texte de la question a bien été pris en compte

**Comment by MestourBS** [comment]
Ce problème ne survient pas de mon côté. Ça pourrait pour certaines questions seulement.

**Comment by DidierViret** [comment]
Probablement un problème de rafraichissement du pdf qui était en cache.
