### ISSUE TITLE
Modification du nom d'un sujet non-enregistrés (nombre max. de caractère atteint)

### ISSUE THREAD

**Issue by RuCaVi** [OrifInformatique/gestion_questionnaires#142]
Lorsque l'on modifie le nom d'un sujet et que l'on clique sur "Enregistrer", cela n'effectue pas l'enregistrement car les modifications ne s'affiche pas, même lorsque que l'on clique de nouveau sur le sujet il affiche l'ancien nom

**Comment by MestourBS** [comment]
Il faudrait mettre un message d'erreur quand le nom dépasse la limite de charactères de la bdd

**Comment by RuCaVi** [comment]
Le problème vient du fait que le nombre max. de caractères (50 caractères) est atteint
