### ISSUE TITLE
Mot de passe trop court ou bien non-correspondant possible lors de la création d'un utilisateur

### ISSUE THREAD

**Issue by RuCaVi** [OrifInformatique/gestion_questionnaires#147]
Lorsque l'on ajoute un utilisateur on peut mettre un mot de passe de moins de 6 caractères (minimum requis sur la page de connexion).
On peut également mettre des mots de passe qui ne se correspondent pas lors de la confirmation du mot de passe.

**Comment by MestourBS** [comment]
Réglé dans #146
