### ISSUE TITLE
Ajouter un bouton 'signaler un problème'

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/gestion_questionnaires#170]
Dans le cas où un utilisateur trouve un bug dans le gestionnaire, il devrait pouvoir le signaler sans se connecter à github.

**Comment by BurkhalterY** [comment]
Ajout d'un formulaire qui poste le problème directement sur GitHub.
Peut-être qu'il serait pas mal de créer un label associé pour qu'on puisse facilement traité les issues ouvertes par les utilisateurs.
