### ISSUE TITLE
Balises HTML h1 - h6

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#171]
https://developer.mozilla.org/fr/docs/Web/HTML/Element/Heading_Elements

J'ai vu récemment cet article sur les balises HTML h1, h2, etc. et j'ai remarqué que notre code ne suit pas toujours les principales règles d'utilisation.

Notamment de ne pas sauter de niveau. Exemple : mettre un h1 puis un h3 sans qu'il n'existe de h2.

**Comment by MestourBS** [comment]
Réglé dans #174
