### ISSUE TITLE
Les compte users peuvent accèder à la page support via l'url

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#206]
Les compte users peuvent aller sur la page de poste d'issue via l'url. Alors qu'ils n'ont pas le bouton dans le menu.

**Comment by MestourBS** [comment]
Est-ce qu'il faudrait leur donner un lien vers la page support ou enlever leur accès?

**Comment by MestourBS** [comment]
Les comptes user peuvent voir le lien vers la page support mais ont l'accès refusé. Il faudrait redonner l'accès ou leur enlever le lien.
