### ISSUE TITLE
Vérification de l'ID lors d'un update.

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#207]
Lorsqu'on modifie manuellement l'ID d'un user dans le formulaire d'update. Il n'y a pas de vérification de l'existence de cet ID et les modifications ne sont pas enregistrées.

Pour vérifier l'ID, je pensais utiliser la règle de CodeIgniter in_list avec la liste de tous les IDs. Sachant que le message d'erreur ne devrait normalement pas s'afficher pour un utilisateur lambda.

**Comment by MestourBS** [comment]
Réglé dans #250
