### ISSUE TITLE
Ajouter une méthode hard_delete dans MY_Model

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/gestion_questionnaires#210]
Dans le cas où `soft_delete` est vrai, l'objet dans la bdd ne peut jamais être supprimer définitevement. Il faudrait ajouter la fonction `hard_delete($id)` (et peut-être aussi `hard_delete_by()` et `hard_delete_my($primary_values)`) pour supprimer l'object au lieu de l'archiver.

**Comment by DidierViret** [comment]
Modifié MY_Model en ajoutant un 2ème paramètre dans les fonctions "delete" et "delete_many". Ce paramètre nommé "$force_hard_delete" a une valeur par défaut à false, si on le passe à true l'objet est supprimé de la base de données quelle que soit la valeur de $soft_delete.
