### ISSUE TITLE
Refaire la mise en page des questionnaires et des corrigés

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#23]
Concevoir une mise en page agréable pour la présentation des questionnaires et corrigés. On peut s'inspirer de la présentation qui était faite avec la version Access (voir fichiers pdf dans le dossier du mandat).
Bien réfléchir à la présentation de chaque type de question et une fois la conception validée, réaliser cette mise en page.

**Comment by LaurentSewer** [comment]
J'ai refais la génération des questionnaires et réponses.
