### ISSUE TITLE
La page de suppression de soi n'a pas de bouton retour

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/gestion_questionnaires#247]
Si on se connecte en administrateur et qu'on va sur sa propre page de suppression, il n'y a aucun bouton de retour affiché.

**Comment by DidierViret** [comment]
C'est une modification à faire dans le module "user" du repository ci_packbase_hmvc. Il faut ensuite reporter cette modification dans gestion_questionnaires.
