### ISSUE TITLE
Pop-up dans l'onglet Sujets

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#28]
Un pop-up "Not Found" apparaît lorsque l'on sélectionne un module.

**Comment by BurkhalterY** [comment]
Le pop-up vient d'une requête AJAX sur http://localhost/gestion_questionnaires/add
Cette page n'existe et fait planter la fonction (js/javascript.js ligne 129).

**Comment by BurkhalterY** [comment]
Finalement, la fonction servait à aller chercher le nombre de questions dans la création de questionnaire.

**Comment by DidierViret** [comment]
La fonction javascript a été déplacée dans la vue questionnaires->add
