### ISSUE TITLE
Génération de questionnaire pas fonctionnelle

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#3]
La génération de questionnaire et corrigé plante selon les sujets sélectionné. Voir si ça dépend du nombre de sujet, nom du sujet, type de question, etc.
Il y a une probabilité pour que ce problème soit lié à la recherche d'un sujet d'après son nom à la place d'utiliser son ID.

controllers\Questionnaire.php [ligne 295]
`$topicLine = $this->topic_model->get_by("Topic = '$topic'");`

**Comment by BurkhalterY** [comment]
Cause de l'erreur : image non trouvée.
J’ai mis une image par défaut si l’image n’existe pas.
(\gestion_questionnaires\application\img\not-found.png)
