### ISSUE TITLE
Génération de questionnaire plante

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#30]
Certaine génération de questionnaire bug quand il y a une question de type cloze text.

Peut-être que ça viens de ma base de données car j'ai 22 questions de type ClozeText mais il n’y a que 20 entrées dans la table t_cloze_text.

**Comment by DidierViret** [comment]
Vérifier si ça vient de la base de données, sinon chercher d'où vient l'erreur.
Si l'erreur vient de la BD, vérifier que l'interface graphique ne permet pas de créer ce type d'erreur.
Gérer le cas dans le code (si le texte n'existe pas dans la BD, remplacer par une chaine vide.

**Comment by BurkhalterY** [comment]
Dans ma base de données, 2 questions n'ont pas de cloze text associé.

**Comment by DidierViret** [comment]
Le champ est requis si on crée une question par l'interface, donc OK.
A l'importation, vérifier que le texte à trous existe et sinon qu'une valeur vide est crée dans la table cloze_text.
Vérifier que le problème ne se produit pas s'il n'y a aucune réponse associée au texte.

**Comment by BurkhalterY** [comment]
Dans l'importation, pour tous les types de questions, si la cellule de la question est vide, alors la question entière n'est pas enregistrer.
Si pour une question cloze_text n'as pas de cloze_text, elle n'est non-plus pas importé.

**Comment by DidierViret** [comment]
A corriger après la release 1.0

**Comment by BurkhalterY** [comment]
Cela est dû à la présence du caractère "" dans la base de données.

**Comment by DidierViret** [comment]
Corrigé le texte dans la base de données du site live
