### ISSUE TITLE
Suppression d'un question présente dans un questionnaire

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#36]
Quand on veut supprimer une question qui est dans un questionnaire, on est redirigé sur une liste de questionnaires sans informations sur ce qu’il faut faire.

**Comment by BurkhalterY** [comment]
Il faudrait ajouter un petit texte expliquant qu'il faut d'abord supprimer tous les questionnaires listé avant de pouvoir supprimer la question. Peut-être ajouter un bouton pour supprimer tous les questionnaires listé en une fois et un bouton sur la même page pour supprimer la question une fois les questionnaires supprimé.

**Comment by DidierViret** [comment]
Si une question fait partie d'un ou plusieurs questionnaires, elle ne doit pas pouvoir être supprimée.
On pourrait prévoir un champ "active" booléen qui permettrait de désactiver une question pour qu'elle ne soit plus listée et plus utilisée dans les nouveaux questionnaires.

Établir une liste des fonctions impactées par ce changement (fichier et No de ligne) avant de le réaliser.

**Comment by BurkhalterY** [comment]
```
models/question_model
	ligne 43: ->where("FK_Topic = $idTopic")
	ligne 54: ->where("FK_Topic = $idTopic")

controllers/Question
	ligne 112: $output['page_limit'] = ceil(count($this->question_model->with_all()->get_all())/20);
	ligne 114: $output['page_limit'] = ceil(count($this->question_model->with_all()->get_many_by($where))/20);
	ligne 120: $output['questions'] = $this->question_model->with_all()->get_all();
	ligne 123: $output['questions'] = $this->question_model->with_all()->get_many_by($where);

controllers/Questionnaire
	ligne 132: $output['questions'] = $this->question_model->with_all()->get_all();
```

On ne pourra plus utiliser le get_all() car il ne faudra plus prendre toutes les questions.
Le mieux serait d'ajouter une fonction dans models/question_model qui prend uniquement les questions actives.
