### ISSUE TITLE
Erreur de filtre

### ISSUE THREAD

**Issue by LaurentSewer** [OrifInformatique/gestion_questionnaires#39]
si on filtre une question par un module qui'ne possède pas de sujet, ça génère une érreure php,
idem si on met une url contenant une question non existante en paramètre 
ex: .../gestion_questionnaires/Question?module=1000&topic=&type=

**Comment by DidierViret** [comment]
Gérer le cas dans le contrôleur (si aucun sujet n'existe, envoyer une entrée vide ou autre astuce).

**Comment by DidierViret** [comment]
Cas traité ensemble dans le bureau, à tester complètement.
