### ISSUE TITLE
Importer images

### ISSUE THREAD

**Issue by LaurentSewer** [OrifInformatique/gestion_questionnaires#42]
le bouton importer une question génère une erreurs quand rien est sélectionné
le bouton importer emmène vers une page blanche quand rien est sélectionné

**Comment by BurkhalterY** [comment]
Je propose de supprimer le if
`if(!isset($error))
{
	redirect("./Question/import");
}`
ainsi, il ne se bloque plus sur une page blanche et retourne à la page d'upload sans rien faire.

**Comment by DidierViret** [comment]
**Pour le bouton "importer"**
Je n'ai pas tout décortiqué en détail, peut-être qu'on peut effectivement enlever le if comme proposé par @BurkhalterY mais il faut traiter le message d'erreur et l'afficher dans la vue, sous le titre "Importer vos images", dans une div de la classe .alert-danger

**Comment by DidierViret** [comment]
Pour le bouton "importer une question", les erreurs PHP venaient d'une mauvaise construction du tableau des topics avant de les passer à la vue.

Corrigé dans le contrôleur Question.php

utiliser
`$this->topic_model->get_tree();`
A la place de 
`$this->topic_model->get_all();`
