### ISSUE TITLE
Ordrer les listes

### ISSUE THREAD

**Issue by LaurentSewer** [OrifInformatique/gestion_questionnaires#51]
rajouter des boutons sur les tables pour trier les éléments dans question/index

**Comment by BurkhalterY** [comment]
Faire ça en JavaScript ou en PHP ?

En PHP, on peut directement utiliser une requête SQL "ORDER BY" mais on doit recharger la page.

**Comment by LaurentSewer** [comment]
l'erreur du dernier commit est surement lié au #57, il y as du avoir des changements involontaires ou inadéquats avec le filtre "Module concerné"

**Comment by LaurentSewer** [comment]
L'érreurs php due au tri sans filtre module était due qu fait que le filtre module ajoutais des parenthèses nécessaire (pour utiliser les ORDER BY avec plusieurs filtres avant) à la requète sql qui n'étaient pas présentes avec les autres filtres
