### ISSUE TITLE
Réviser le code de la génération de questionnaire

### ISSUE THREAD

**Issue by LaurentSewer** [OrifInformatique/gestion_questionnaires#55]
form_add(), generatePDF(), InsertNewQuestionnaire() devraient être améliorées.

**Comment by MestourBS** [comment]
`generatePDF()` et `InsertNewQuestionnaire()` ont été partiellement réécrit dans #114

**Comment by DidierViret** [comment]
Peut encore être révisé dans le cadre d'améliorations continues, mais la version actuelle est fonctionnelle.
