### ISSUE TITLE
Types de question qui ne marchent pas

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/gestion_questionnaires#67]
Les types de question Choix multiples et Texte à trous affichent des erreurs

À voir aussi si on garde les 2 types de questions non-implémentés dans la liste déroulantes.

**Comment by DidierViret** [comment]
Oui, on garde tous les types de questions dans la liste déroulante. Ajouter un message d'erreur si on choisi un type de question non implémenté (ou désactiver les éléments de la liste).

Corriger le bug pour les Choix multiples et Texte à trous.

**Comment by BurkhalterY** [comment]
Les 2 types de questions qui plantaient ont été réparés et un message apparait lorsqu’on essaye de créer une question de type Distribution de réponse ou Tableau.
