### ISSUE TITLE
Retravailler la mise en page des questionnaires et des corrigés

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#72]
Valider une mise en page avec les MSP du secrétariat médical et la mettre en place.
Faire en sorte de rendre l'aspect de ces questionnaires le plus agréable possible.

**Comment by DidierViret** [comment]
Je joins un exemple de mise en page.
Vous pouvez déjà commencer à y travailler mais **je dois encore le valider avec mes collègues
** du secrétariat médical et il y aura donc des modifications (peut-être importantes).
[questionnaires_secr_medical_modele.pdf](https://github.com/OrifInformatique/gestion_questionnaires/files/3302031/questionnaires_secr_medical_modele.pdf)

**Comment by DidierViret** [comment]
Modifier l'interligne (plus petit).
Fixer le numéro de page en bas à droite.
Changer le logo.

**Comment by MestourBS** [comment]
Numéro et logo réglés dans MeSa

**Comment by DidierViret** [comment]
Version pour la release 1.1 terminée, à tester et valider avec le client.
