### ISSUE TITLE
Bloquer le choix d'un sujet qui a déjà été ajouté dans la génération de questionnaire

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#77]
Lorsqu'on prépare la génération d'un questionnaire, il est possible d'ajouter plusieurs fois le même sujet. Il faut bloquer cette possibilité.

Ajouter la possibilité de supprimer un sujet qui est déjà dans la liste, puis de le remettre.

**Comment by BurkhalterY** [comment]
Salah et moi avons tous les deux fait les modifications nécessaires, il faudrait regarder pour voir laquelle des deux on garde.

**Comment by MestourBS** [comment]
Fermée avec #85
