### ISSUE TITLE
Certaine modification dans les question non-enregister

### ISSUE THREAD

**Issue by RuCaVi** [OrifInformatique/gestion_questionnaires#83]
Si on modifie une réponse d'une question "ChoixMultiple" et que l'on clique sur enregistrer les modification ne sont pas sauvegarder, car si on retourne modifier la question on voit que les modifications ne sont pas présente.

Et pour les questions "ReponseMultiples", si on change le nombre de réponse attendue et bien cela n'es pas appliquer lors de l’enregistrement.

**Comment by DidierViret** [comment]
La partie "ReponseMultiples" n'est pas corrigée, mais reportée dans une nouvelle Issue #91
