### ISSUE TITLE
Correct the content of the live site's database

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/gestion_questionnaires#98]
Check the structure of every question in the live site's database :
- Change the type of question if the wrong type is selected
- Add missing answers in multiple answers (for example OUI / NON instead of just OUI)
- Check the symbol for missing words in cloze texts [...]
- etc.

To do this, talk together at first, to chose who will check each group of questions. Make sur you don't forget any group.

**Comment by BurkhalterY** [comment]
Répartition des questions :
Salah : 1 – 57
Yannis : 58 – 114
Ruben : 115 – 171

**Comment by BurkhalterY** [comment]
Pour la question ID = 35, il manque la fin des repères.
